# -*- coding: utf-8 -*-
"""customers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YYhalkWL8ARiVj3rSJ8HXix_G92Ap4AR

# Stout Case Study #2: Customer Orders
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib.image as mpimg


import warnings
warnings.filterwarnings("ignore")

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Stout/casestudy.csv",index_col=0)

df.head()

"""- Total revenue for the current year"""

pd.DataFrame(df.groupby(['year'])['net_revenue'].agg('sum'))

"""- Total Customers Current Year"""

pd.DataFrame(df.groupby("year").customer_email.count())

"""- Total Customers Previous Year"""

pd.DataFrame(df.groupby("year").customer_email.count()).shift(1)

"""- New Customers"""

c2015 = df[df["year"]==2015]
c2016 = df[df["year"]==2016]
c2017 = df[df["year"]==2017]
new_2017=pd.merge(c2017, c2016, how='outer',on="customer_email",indicator=True).query('_merge == "left_only"').drop(columns=['_merge',"net_revenue_y","year_y"])
new_2016=pd.merge(c2016, c2015, how='outer',on="customer_email",indicator=True).query('_merge == "left_only"').drop(columns=['_merge',"net_revenue_y","year_y"])
new_customers=pd.concat([new_2017,new_2016],axis=0)
new_customers.columns=["customer_email","net_revenue","year"]
pd.DataFrame(new_customers["year"].value_counts())

"""- New customers revenue"""

pd.DataFrame(new_customers.groupby("year")["net_revenue"].agg("sum"))

"""- Lost customers"""

lost_2017=pd.merge(c2016, c2017, how='outer',on="customer_email",indicator=True).query('_merge == "left_only"').drop(columns=['_merge',"net_revenue_y","year_y"])
lost_2016=pd.merge(c2015, c2016, how='outer',on="customer_email",indicator=True).query('_merge == "left_only"').drop(columns=['_merge',"net_revenue_y","year_y"])
lost_customers=pd.concat([new_2017,new_2016],axis=0)
lost_customers.columns=["customer_email","net_revenue","year"]
pd.DataFrame(lost_customers["year"].value_counts())

"""- Revenue lost from attrition"""

pd.DataFrame(lost_customers.groupby("year")["net_revenue"].agg("sum"))

"""- Existing customer growth"""

pd.DataFrame(pd.DataFrame(df.groupby(['year'])['net_revenue'].agg('sum'))['net_revenue']-pd.DataFrame(df.groupby(['year'])['net_revenue'].agg('sum')).shift(1)['net_revenue'])

"""- Existing Customer Revenue Current Year """

pd.DataFrame(df.groupby("year").net_revenue.agg(sum))

"""- Existing Customer Revenue Previous Year """

pd.DataFrame(df.groupby("year").net_revenue.agg(sum)).shift(1)

"""- Some visualizations"""

df.plot.box()

plt.hist(df["net_revenue"],density=True)

"""We can see here that the distribution of the net revenues is quite uniform."""